services:
  nginx:
    image: ubuntu/nginx
    ports:
      - 8080:80
      - 443:443
    volumes:
      - ./content/:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt